### ISSUE TITLE
Build Failes on piwheels.org

### ISSUE THREAD

**Issue by niccokunzmann** [samuelcolvin/watchfiles#206] opened 2022-11-10 18:59 UTC
### Description

piwheels cannot build this so it it not well available for the Raspberry Pi.
https://www.piwheels.org/project/watchfiles/
https://www.piwheels.org/logs/0000/0896/9806.txt

### Operating System & Architecture

Linux-5.10.63-v7l+-armv7l-with-debian-10.11
#1496 SMP Wed Dec 1 15:58:56 GMT 2021

### Python & Watchfiles Version

??

### Rust & Cargo Version

??

**Comment by samuelcolvin** [comment] 2022-11-10 20:17
Duplicate of #149.

Run

```bash
pip install -i https://pypi.org/simple/ watchfiles
```

**Closed by samuelcolvin** 2022-11-10 20:17 UTC
Labels: bug

**Comment by samuelcolvin** [comment] 2022-11-10 20:18
See also https://github.com/piwheels/packages/issues/304. Nothing I can do until they fix it.
