### ISSUE TITLE
Problems when using vim - `Remove(File)` event when saving the file

### ISSUE THREAD

**Issue by sapristi** [samuelcolvin/watchfiles#215] opened 2022-11-27 23:28 UTC
### Description

Hello, 
and thanks for providing `watchfiles` ! I seem to have an issue occuring with `vim` specifically, so I'm not sure this is the best place for a bug report, but this could always serve as future reference:

When editing then saving a file in `vim` (version 9.0.813), for some reason a `Remove(File)` event is sent; no sub-sequent events are received when modifying the file:

```
raw-event: Event { kind: Modify(Name(From)), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Metadata(Any)), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Remove(File), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```

Note that:
 - the same happens when running `watchfiles 'echo reloaded' config.yaml --verbose`
 - when running `watchfiles 'echo reloaded' . --verbose`, the behaviour is actually different (and the problem doesn't seem to arise):
```
[00:25:43] watchfiles v0.18.1 👀  path="/home/sapristi/dev/mmuxer" target="echo reloaded" (command) filter=DefaultFilter...
[00:25:43] running "echo reloaded" as command
reloaded
watcher: INotifyWatcher { channel: Sender { .. }, waker: Waker { inner: Waker { fd: File { fd: 5, path: "anon_inode:[eventfd]", read: true, write: true } } } }
raw-event: Event { kind: Create(File), paths: ["/home/sapristi/dev/mmuxer/4913"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Metadata(Any)), paths: ["/home/sapristi/dev/mmuxer/4913"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Access(Close(Write)), paths: ["/home/sapristi/dev/mmuxer/4913"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Remove(File), paths: ["/home/sapristi/dev/mmuxer/4913"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Name(From)), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: Some(3873), attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Create(File), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Data(Any)), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Metadata(Any)), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Access(Close(Write)), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Metadata(Any)), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
[00:25:46] 4 changes detected: {(<Change.deleted: 3>, '/home/sapristi/dev/mmuxer/4913'), (<Change.added: 1>, '/home/sapristi/dev/mmuxer/4913'), (<Change.deleted: 3>, '/home/sapristi/dev/mmuxer/config.yaml'), (<Change.added: 1>, '/home/sapristi/dev/mmuxer/config.yaml')}
[00:25:46] process already dead, exit code: 0
reloaded
[00:25:51] rust notify timeout, continuing
^C[00:25:54] KeyboardInterrupt caught, stopping watch
```

### Example Code

```Python
from threading import Thread, Event

class WatcherWorker(Thread):
    def run(self):
        for change in watch("config.yaml", debug=True):
            print(change)
            flag.set()

WatcherWorker().start()
```

### Watchfiles Output

```Text
raw-event: Event { kind: Modify(Name(From)), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Modify(Metadata(Any)), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
raw-event: Event { kind: Remove(File), paths: ["/home/sapristi/dev/mmuxer/config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }
```

### Operating System & Architecture

Linux-5.15.76-1-MANJARO-x86_64-with-glibc2.36
#1 SMP PREEMPT Sat Oct 29 14:22:16 UTC 2022

### Environment

Installed in a virtualenv, nothing fancy.

### Python & Watchfiles Version

python: 3.10.8 (main, Oct 13 2022, 21:13:48) [GCC 12.2.0], watchfiles: 0.18.1

**Comment by samuelcolvin** [comment] 2022-11-28 10:38
Thanks for reporting, so weird.

I know vim creates numerous temporary files, but I really don't understand why you're seeing a `Remove(File)` instead of `Create(File)` specifically when watching one file.

A few things to try:
* do you get the correct output when you force polling?
* The raw-events are literally the raw events from [the `notify` crate](https://github.com/notify-rs/notify) it might be worth looking at their issue or even asking there

**Comment by sapristi** [comment] 2022-11-29 12:33
So
- when force-polling,  the only event received upon saving the file with vim is   
  `raw-event: Event { kind: Modify(Metadata(WriteTime)), paths: ["config.yaml"], attr:tracker: None, attr:flag: None, attr:info: None, attr:source: None }`  
  -> subsequent writes are detected :)
- the issue was already reported in libnotify, with some explanations https://github.com/notify-rs/notify/issues/394

Thanks for your quick feedback !

**Comment by samuelcolvin** [comment] 2022-11-29 13:02
Great, well found.

I'll close this since the issue is tracked in https://github.com/notify-rs/notify/issues/394

**Closed by samuelcolvin** 2022-11-29 13:02 UTC
Labels: bug
