### ISSUE TITLE
M1 mac with Docker WatchfilesRustInternalError: Error creating watcher: Function not implemented (os error 38)

### ISSUE THREAD

**Issue by daniel-butler** [samuelcolvin/watchfiles#167] opened 2022-07-10 23:49 UTC
### Description

When starting django with the watcher (after installing from pypi from the wheel)

```
PostgreSQL is available
INFO:     Will watch for changes in these directories: ['/app']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [18] using WatchFiles
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
=== Starting migration
Operations to perform:
  Apply all migrations: account, address, admin, auth, contenttypes, customers, orders_tenant, permissions, sessions, socialaccount, users
Running migrations:
  No migrations to apply.
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 407, in main
    run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 570, in run
    ChangeReload(config, target=server.run, sockets=[sock]).run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/supervisors/basereload.py", line 45, in run
    for changes in self:
  File "/usr/local/lib/python3.9/site-packages/uvicorn/supervisors/basereload.py", line 64, in __next__
    return self.should_restart()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/supervisors/watchfilesreload.py", line 85, in should_restart
    changes = next(self.watcher)
  File "/usr/local/lib/python3.9/site-packages/watchfiles/main.py", line 103, in watch
    watcher = RustNotify([str(p) for p in paths], debug, force_polling, poll_delay_ms)
_rust_notify.WatchfilesRustInternalError: Error creating watcher: Function not implemented (os error 38)
```

### Operating System

Mac M1 12.3.1 (21E258)

### Environment

Docker

### Watchfiles Version

0.15.0

### Python Version

3.9

### Rust & Cargo Version

cargo: not found; rustc: not found

**Comment by samuelcolvin** [comment] 2022-07-11 07:48
Which docker image?

**Comment by samuelcolvin** [comment] 2022-07-12 08:31
Maybe worth checking if the correct wheel was installed.

I've run watchfiles inside docket on my M1 Mac and it worked fine.

**Comment by br3ndonland** [comment] 2022-07-16 21:07
I can reproduce this without Django or Uvicorn. The error occurs on an Apple Silicon M1 Mac, but not on an Intel Mac, and occurs even if specifying the platform.

watch.py

```py
from watchfiles import watch

for changes in watch('/hello.py'):
    print(changes)
```

hello.py

```py
print('hello world')
```

Dockerfile

```dockerfile
FROM python:3.10
RUN pip install watchfiles==0.15.0
COPY hello.py watch.py /
CMD watchfiles watch /hello.py
```

```sh
docker build . --platform linux/amd64 -t watchfiles-example
docker run -p 8080:80  --platform linux/amd64 -v "$(pwd)/hello.py":"/hello.py" watchfiles-example
```

```text
[20:55:51] watchfiles 👀  path="/hello.py" target="watch" (command) filter=DefaultFilter...
Traceback (most recent call last):
  File "/usr/local/bin/watchfiles", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/site-packages/watchfiles/cli.py", line 150, in cli
    run_process(
  File "/usr/local/lib/python3.10/site-packages/watchfiles/run.py", line 130, in run_process
    for changes in watch(
  File "/usr/local/lib/python3.10/site-packages/watchfiles/main.py", line 103, in watch
    watcher = RustNotify([str(p) for p in paths], debug, force_polling, poll_delay_ms)
_rust_notify.WatchfilesRustInternalError: Error creating watcher: Function not implemented (os error 38)
```

Consider reporting to Docker upstream (docker/roadmap#7).

**Comment by gravy-jones-locker** [comment] 2022-07-19 14:03
+1 on this

**Comment by samuelcolvin** [comment] 2022-07-19 16:32
Okay, I can reproduce this.

First the good news:
1. I don't get this error (and watchfiles seems to correctly detect changes) if I remove `--platform linux/amd64`
2. Same if I use `force_polling=True`
3. As per the traceback, watchfiles is catching this error, so we should be able to catch the error and gracefully fall back to polling

It might also be worth honouring an env variable to enable polling for those who are using watchfiles via a third party library and therefore aren't able to use the kwarg directly.

In terms of the underlying error and how to handle it, I'm not really sure where to go.

@messense do you have any ideas?

**Comment by samuelcolvin** [comment] 2022-07-19 16:36
From the logs, pip is installing `watchfiles-0.15.0-cp37-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.whl`. 

I tried packing pip to allow me to install other wheels directly and tried installing `
watchfiles-0.15.0-cp37-abi3-manylinux_2_17_armv7l.manylinux2014_armv7l.whl` and `watchfiles-0.15.0-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl ` on the off-chance that worked, but it gave me a `wrong ELF class: ELFCLASS32` error.

I also tried install 0.14.1 in case it was an issue with abi3, but it doesn't seem to be.

**Comment by messense** [comment] 2022-07-20 02:19
I cannot reproduce this with [lima](https://github.com/lima-vm/lima) on M1 Pro Mac.

```bash
root@49fb5ab8d2ea:/# watchfiles watch /hello.py
[02:19:00] watchfiles 👀  path="/hello.py" target="watch" (command) filter=DefaultFilter...

Usage:
 watch [options] command

Options:
  -b, --beep             beep if command has a non-zero exit
  -c, --color            interpret ANSI color and style sequences
  -d, --differences[=<permanent>]
                         highlight changes between updates
  -e, --errexit          exit if command has a non-zero exit
  -g, --chgexit          exit when output from command changes
  -n, --interval <secs>  seconds to wait between updates
  -p, --precise          attempt run command in precise intervals
  -t, --no-title         turn off header
  -w, --no-wrap          turn off line wrapping
  -x, --exec             pass command to exec instead of "sh -c"

 -h, --help     display this help and exit
 -v, --version  output version information and exit

For more details see watch(1).
^C[02:19:03] KeyboardInterrupt caught, stopping watch
[02:19:03] process already dead, exit code: 1
```

**Comment by samuelcolvin** [comment] 2022-07-20 07:41
I think I'll ask on notify and see if they have any ideas.

**Comment by samuelcolvin** [comment] 2022-07-20 09:38
Partial fix / work around building now in #170.

Reported upstream, see https://github.com/notify-rs/notify/issues/423.

**Comment by messense** [comment] 2022-07-20 09:54
FYI, https://docs.docker.com/desktop/mac/apple-silicon/#known-issues

> However, attempts to run Intel-based containers on Apple silicon machines under emulation can crash as qemu sometimes fails to run the container. **In addition, filesystem change notification APIs (inotify) do not work under qemu emulation.**

**Comment by samuelcolvin** [comment] 2022-07-20 12:49
Okay, this is fixed in #172.

**Please could those experiencing this problem @daniel-butler @br3ndonland @gravy-jones-locker try this and confirm it fixes the problem for you.**

To install from wheel from the PR:
* Download `pypi_files` from [the CI run](https://github.com/samuelcolvin/watchfiles/actions/runs/2704613281)
* Extract the zip
*  `pip install pypi_files/watchfiles-0.0.0-cp37-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.whl`

**Comment by daniel-butler** [comment] 2022-07-20 16:02
It is working for me when I use the updated wheel! Thank you for fixing!

**Comment by samuelcolvin** [comment] 2022-07-20 17:08
Great, trunk you for confirming. I'll make a new release tomorrow.

**Closed** 2022-07-21 10:47 UTC
Labels: bug

**Comment by samuelcolvin** [comment] 2022-07-21 14:25
**v0.16.0** has just be released.

**Comment by daniel-butler** [comment] 2022-07-22 01:38
Nice! It works with 0.16.0 from PyPI, too.

**Comment by gravy-jones-locker** [comment] 2022-07-29 07:43
missed the notifications for these. but the immediate issue is definitely fixed. thanks!
